### PR TITLE
Telephone-Number-Validator

### PR DESCRIPTION
**Pull request by WALWALASAFI**
telephone number validator is a tool or form designed to verify whether a given input matches the expected format of a phone number. that includes index.html, styles.css and JavaScript file.

### CODE REVIEW

**Comment by WALWALASAFI** [comment]
Hi dear @ZohalMirkhel
look at my project

**Comment by ZohalMirkhel** [comment]
Dear @WALWALASAFI, I reviewed your project and it functions well. However, the HTML code could be cleaner, and the website is not responsive. I think you may want to address these issues.

**Comment by WALWALASAFI** [comment]
@ZohalMirkhel 
i have given some more responsive (media query)

**Comment by WALWALASAFI** [comment]
HI Dear sir @ahzamir,
i hope ur fine and doing great 
kindly check my project 
also, share your feedback as soon as possible dear sir

**Comment by WALWALASAFI** [comment]
@ahzamir
Hi dear sir,
i hope ur fine and doing great.
i am still waiting for feedback however it went 2 days from it.
couldu you check it dear sir,

**Review by ahzamir — CHANGES_REQUESTED** [review]
- Well done @WALWALASAFI  Your project functionality is perfect and also the design is great:
image

- Just your project has some issues for the mobile version please make your project responsive and mention me back here to re-review your project:
image

**Comment by WALWALASAFI** [comment]
@ZohalMirkhel

**Comment by ZohalMirkhel** [comment]
Dear @WALWALASAFI, I checked your project, and it is still not responsive, I believe you can do some more work on it. Thank you!

**Comment by WALWALASAFI** [comment]
@ahzamir  Hi dear sir,
i have added media query to be responsive. 
thanks in advance

**Review by ahzamir — APPROVED** [review]
### Hi @WALWALASAFI 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Telephone Number Validator project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
